### ISSUE TITLE
useFormContext cannot be used because register is of undefined union type

### ISSUE THREAD

**Issue by minai621** [dbssman/vue-form-handler#73]
The current useFormContext function has an issue where the returned value from the inject function can be undefined, causing a need to validate the stability of register. However, since defaultInjectionKey is provided, there is no actual scenario where undefined would be returned.

Solution
Updated the useFormContext function to cast the injected value to FormHandlerReturn<T> directly, ensuring it is always a valid context.

**Comment by dbssman** [comment]
Your contribution was included in the v1 release :)
